# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.ticket import Ticket

class TestTicket(unittest.TestCase):
    """Ticket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ticket:
        """Test Ticket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ticket`
        """
        model = Ticket()
        if include_optional:
            return Ticket(
                id = '',
                operator_id = 56,
                operator_name = '',
                numero = '',
                etat = '',
                etat_lib = '',
                titre = '',
                cust_name = '',
                ref_commande = '',
                id_service_sicom = 56,
                ref_service = '',
                cust_address = '',
                ref_tiers = '',
                date_creation = '',
                date_ouverture = '',
                date_resolution = '',
                date_cloture = '',
                last_message = '',
                running_process = [
                    prizz_extranet.models.running_process.RunningProcess(
                        id = 56, 
                        lib = '', 
                        state = '', 
                        status_code = 56, 
                        create_date = '', 
                        process_class = '', )
                    ]
            )
        else:
            return Ticket(
        )
        """

    def testTicket(self):
        """Test Ticket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
