# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.process_attributes_messages import ProcessAttributesMessages

class TestProcessAttributesMessages(unittest.TestCase):
    """ProcessAttributesMessages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessAttributesMessages:
        """Test ProcessAttributesMessages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessAttributesMessages`
        """
        model = ProcessAttributesMessages()
        if include_optional:
            return ProcessAttributesMessages(
                operateur = [
                    prizz_extranet.models.process_message.ProcessMessage(
                        date = '', 
                        format = '', 
                        author = '', 
                        freeze = True, 
                        from_us = True, 
                        message = '', )
                    ],
                noc = [
                    prizz_extranet.models.process_message.ProcessMessage(
                        date = '', 
                        format = '', 
                        author = '', 
                        freeze = True, 
                        from_us = True, 
                        message = '', )
                    ],
                terrain = [
                    prizz_extranet.models.process_message.ProcessMessage(
                        date = '', 
                        format = '', 
                        author = '', 
                        freeze = True, 
                        from_us = True, 
                        message = '', )
                    ]
            )
        else:
            return ProcessAttributesMessages(
        )
        """

    def testProcessAttributesMessages(self):
        """Test ProcessAttributesMessages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
