# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.workflow import Workflow

class TestWorkflow(unittest.TestCase):
    """Workflow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Workflow:
        """Test Workflow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Workflow`
        """
        model = Workflow()
        if include_optional:
            return Workflow(
                id = 56,
                title = '',
                context = '',
                entity_id = 56,
                entity_class = '',
                state = '',
                html = '',
                transitions = [
                    prizz_extranet.models.transition.Transition(
                        name = '', 
                        html = '', 
                        form_fields = [
                            prizz_extranet.models.transition_form_fields_inner.Transition_formFields_inner(
                                caption = '', 
                                name = '', 
                                required = True, 
                                value = '', 
                                values = [
                                    prizz_extranet.models.transition_form_fields_inner_values_inner.Transition_formFields_inner_values_inner(
                                        key = '', 
                                        value = '', )
                                    ], 
                                type = '', 
                                help = '', 
                                multiple = True, 
                                expanded = True, )
                            ], )
                    ]
            )
        else:
            return Workflow(
        )
        """

    def testWorkflow(self):
        """Test Workflow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
