# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.rename_commercial_offer_section import RenameCommercialOfferSection

class TestRenameCommercialOfferSection(unittest.TestCase):
    """RenameCommercialOfferSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenameCommercialOfferSection:
        """Test RenameCommercialOfferSection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenameCommercialOfferSection`
        """
        model = RenameCommercialOfferSection()
        if include_optional:
            return RenameCommercialOfferSection(
                name = ''
            )
        else:
            return RenameCommercialOfferSection(
        )
        """

    def testRenameCommercialOfferSection(self):
        """Test RenameCommercialOfferSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
