# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.get_api_tokens200_response import GetApiTokens200Response

class TestGetApiTokens200Response(unittest.TestCase):
    """GetApiTokens200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiTokens200Response:
        """Test GetApiTokens200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiTokens200Response`
        """
        model = GetApiTokens200Response()
        if include_optional:
            return GetApiTokens200Response(
                pagination = prizz_extranet.models.get_client_legal_entities_200_response_pagination.getClientLegalEntities_200_response_pagination(
                    page = 56, 
                    items_per_page = 56, 
                    total_items = 56, 
                    page_count = 56, ),
                items = [
                    prizz_extranet.models.user_api_token.UserApiToken(
                        available_workflows = [
                            'Infracorp\\Services\\Workflow\\ClientLegalEntity\\CreateCommercialOffer\\Context'
                            ], 
                        create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = 56, 
                        name = '', 
                        active = True, 
                        token = '', 
                        last_usage = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetApiTokens200Response(
        )
        """

    def testGetApiTokens200Response(self):
        """Test GetApiTokens200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
