# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.process import Process

class TestProcess(unittest.TestCase):
    """Process unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Process:
        """Test Process
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Process`
        """
        model = Process()
        if include_optional:
            return Process(
                context_id = 56,
                entity_id = 56,
                entity_class = '',
                process_class = '',
                start_date = '',
                state = '',
                state_lib = '',
                end_date = '',
                attrs = { },
                lib = '',
                title = '',
                states = [
                    null
                    ],
                attachments = [
                    prizz_extranet.models.ticket_attachment.TicketAttachment(
                        preview_url = '', 
                        url = '', 
                        name = '', 
                        key = '', )
                    ],
                actions = [
                    prizz_extranet.models.process_action.ProcessAction(
                        id = '', 
                        lib = '', 
                        classe = '', 
                        html = '', 
                        default = '', 
                        fields = [
                            prizz_extranet.models.process_action_field.ProcessActionField(
                                caption = '', 
                                type = '', 
                                value = '', 
                                name = '', 
                                values = [
                                    null
                                    ], 
                                required = True, )
                            ], )
                    ]
            )
        else:
            return Process(
        )
        """

    def testProcess(self):
        """Test Process"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
