# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.offer_context_shortened import OfferContextShortened

class TestOfferContextShortened(unittest.TestCase):
    """OfferContextShortened unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OfferContextShortened:
        """Test OfferContextShortened
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OfferContextShortened`
        """
        model = OfferContextShortened()
        if include_optional:
            return OfferContextShortened(
                offer_id = 56,
                total = 56,
                total_without_nrc = 56,
                has_to_estimate_products = True,
                items_ids = [
                    56
                    ],
                attributes = { }
            )
        else:
            return OfferContextShortened(
        )
        """

    def testOfferContextShortened(self):
        """Test OfferContextShortened"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
