# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.sign_commercial_offer200_response import SignCommercialOffer200Response

class TestSignCommercialOffer200Response(unittest.TestCase):
    """SignCommercialOffer200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignCommercialOffer200Response:
        """Test SignCommercialOffer200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignCommercialOffer200Response`
        """
        model = SignCommercialOffer200Response()
        if include_optional:
            return SignCommercialOffer200Response(
                id = 56,
                success = True,
                last_log = '',
                step = 'codeSent'
            )
        else:
            return SignCommercialOffer200Response(
        )
        """

    def testSignCommercialOffer200Response(self):
        """Test SignCommercialOffer200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
