# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.add_service_contract_comment import AddServiceContractComment

class TestAddServiceContractComment(unittest.TestCase):
    """AddServiceContractComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddServiceContractComment:
        """Test AddServiceContractComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddServiceContractComment`
        """
        model = AddServiceContractComment()
        if include_optional:
            return AddServiceContractComment(
                title = '',
                thread_id = 56,
                parent_id = 56,
                content_type = 'text',
                content = ''
            )
        else:
            return AddServiceContractComment(
        )
        """

    def testAddServiceContractComment(self):
        """Test AddServiceContractComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
