# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.commercial_offer_search import CommercialOfferSearch

class TestCommercialOfferSearch(unittest.TestCase):
    """CommercialOfferSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommercialOfferSearch:
        """Test CommercialOfferSearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommercialOfferSearch`
        """
        model = CommercialOfferSearch()
        if include_optional:
            return CommercialOfferSearch(
                index = '',
                query = '',
                id = '',
                legal_entity_id = '',
                client_legal_entity_id = '',
                name = '',
                notes = '',
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                section_names = '',
                addresses = [
                    ''
                    ]
            )
        else:
            return CommercialOfferSearch(
        )
        """

    def testCommercialOfferSearch(self):
        """Test CommercialOfferSearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
