# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.invoice_detail import InvoiceDetail

class TestInvoiceDetail(unittest.TestCase):
    """InvoiceDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceDetail:
        """Test InvoiceDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceDetail`
        """
        model = InvoiceDetail()
        if include_optional:
            return InvoiceDetail(
                available_workflows = [
                    'Infracorp\\Services\\Workflow\\ClientLegalEntity\\CreateCommercialOffer\\Context'
                    ],
                id = 56,
                unit_price = 56,
                unit_price_str = '',
                unit = '',
                vat = '',
                recurrence = 'monthly',
                quantity = 56,
                unit_price_discount = 56,
                unit_price_discount_str = '',
                name = '',
                house_number = 56,
                house_number_complement = '',
                street_name = '',
                postal_code = '',
                city_name = '',
                insee_code = '',
                latitude = 1.337,
                longitude = 1.337,
                x = 1.337,
                y = 1.337,
                projection = '',
                amount = 56,
                invoice_id = 56,
                amount_str = '',
                va_trate = 1.337,
                service_id = 56,
                service_contract_id = 56,
                description = '',
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return InvoiceDetail(
        )
        """

    def testInvoiceDetail(self):
        """Test InvoiceDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
