# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.get_workflow_redirect import GetWorkflowRedirect

class TestGetWorkflowRedirect(unittest.TestCase):
    """GetWorkflowRedirect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkflowRedirect:
        """Test GetWorkflowRedirect
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWorkflowRedirect`
        """
        model = GetWorkflowRedirect()
        if include_optional:
            return GetWorkflowRedirect(
                object_class = '',
                object_id = 56
            )
        else:
            return GetWorkflowRedirect(
        )
        """

    def testGetWorkflowRedirect(self):
        """Test GetWorkflowRedirect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
