# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.commercial_offer_vat_detail_str_inner import CommercialOfferVatDetailStrInner

class TestCommercialOfferVatDetailStrInner(unittest.TestCase):
    """CommercialOfferVatDetailStrInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommercialOfferVatDetailStrInner:
        """Test CommercialOfferVatDetailStrInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommercialOfferVatDetailStrInner`
        """
        model = CommercialOfferVatDetailStrInner()
        if include_optional:
            return CommercialOfferVatDetailStrInner(
                vat = 1.337,
                total_without_taxes = '',
                total = ''
            )
        else:
            return CommercialOfferVatDetailStrInner(
        )
        """

    def testCommercialOfferVatDetailStrInner(self):
        """Test CommercialOfferVatDetailStrInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
