# coding: utf-8

"""
    Prizz-Telecom Extranet API

    Prizz-Telecom Extranet API https://dev.prizz-telecom.fr/

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.appointment_tech import AppointmentTech

class TestAppointmentTech(unittest.TestCase):
    """AppointmentTech unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppointmentTech:
        """Test AppointmentTech
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppointmentTech`
        """
        model = AppointmentTech()
        if include_optional:
            return AppointmentTech(
                available_workflows = [
                    'Infracorp\\Services\\Workflow\\ClientLegalEntity\\CreateCommercialOffer\\Context'
                    ],
                id = 56,
                firstname = '',
                lastname = '',
                company_name = '',
                email = '',
                phone1 = '',
                phone2 = '',
                gender = '',
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AppointmentTech(
        )
        """

    def testAppointmentTech(self):
        """Test AppointmentTech"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
