# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.get_running_workflows200_response import GetRunningWorkflows200Response

class TestGetRunningWorkflows200Response(unittest.TestCase):
    """GetRunningWorkflows200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRunningWorkflows200Response:
        """Test GetRunningWorkflows200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRunningWorkflows200Response`
        """
        model = GetRunningWorkflows200Response()
        if include_optional:
            return GetRunningWorkflows200Response(
                workflows = [
                    prizz_extranet.models.get_running_workflows_200_response_workflows_inner.getRunningWorkflows_200_response_workflows_inner(
                        id = 56, 
                        state = '', 
                        context = '', 
                        create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_run_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        entity_class = '', 
                        entity_id = 56, 
                        entity_description = 56, 
                        description = '', 
                        status_code = 56, 
                        last_log = '', 
                        html = '', )
                    ]
            )
        else:
            return GetRunningWorkflows200Response(
        )
        """

    def testGetRunningWorkflows200Response(self):
        """Test GetRunningWorkflows200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
