# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.client_legal_entity_search import ClientLegalEntitySearch

class TestClientLegalEntitySearch(unittest.TestCase):
    """ClientLegalEntitySearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientLegalEntitySearch:
        """Test ClientLegalEntitySearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientLegalEntitySearch`
        """
        model = ClientLegalEntitySearch()
        if include_optional:
            return ClientLegalEntitySearch(
                index = '',
                query = '',
                id = '',
                legal_entity_ids = [
                    ''
                    ],
                name = '',
                address = '',
                siren = '',
                tel = '',
                email = '',
                contacts = [
                    prizz_extranet.models.contact_search.ContactSearch(
                        id = '', 
                        name = '', 
                        company_name = '', 
                        phone1 = '', 
                        phone2 = '', )
                    ]
            )
        else:
            return ClientLegalEntitySearch(
        )
        """

    def testClientLegalEntitySearch(self):
        """Test ClientLegalEntitySearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
