# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.create_operator import CreateOperator

class TestCreateOperator(unittest.TestCase):
    """CreateOperator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOperator:
        """Test CreateOperator
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOperator`
        """
        model = CreateOperator()
        if include_optional:
            return CreateOperator(
                id = 56,
                code = '',
                lib = ''
            )
        else:
            return CreateOperator(
        )
        """

    def testCreateOperator(self):
        """Test CreateOperator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
