# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.create_commercial_offer201_response import CreateCommercialOffer201Response

class TestCreateCommercialOffer201Response(unittest.TestCase):
    """CreateCommercialOffer201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCommercialOffer201Response:
        """Test CreateCommercialOffer201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCommercialOffer201Response`
        """
        model = CreateCommercialOffer201Response()
        if include_optional:
            return CreateCommercialOffer201Response(
                id = 56,
                success = True,
                last_log = ''
            )
        else:
            return CreateCommercialOffer201Response(
        )
        """

    def testCreateCommercialOffer201Response(self):
        """Test CreateCommercialOffer201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
