# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.get_client_legal_entities200_response_pagination import GetClientLegalEntities200ResponsePagination

class TestGetClientLegalEntities200ResponsePagination(unittest.TestCase):
    """GetClientLegalEntities200ResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClientLegalEntities200ResponsePagination:
        """Test GetClientLegalEntities200ResponsePagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClientLegalEntities200ResponsePagination`
        """
        model = GetClientLegalEntities200ResponsePagination()
        if include_optional:
            return GetClientLegalEntities200ResponsePagination(
                page = 56,
                items_per_page = 56,
                total_items = 56,
                page_count = 56
            )
        else:
            return GetClientLegalEntities200ResponsePagination(
        )
        """

    def testGetClientLegalEntities200ResponsePagination(self):
        """Test GetClientLegalEntities200ResponsePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
