# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from prizz_extranet.models.process_action import ProcessAction

class TestProcessAction(unittest.TestCase):
    """ProcessAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessAction:
        """Test ProcessAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessAction`
        """
        model = ProcessAction()
        if include_optional:
            return ProcessAction(
                id = '',
                lib = '',
                classe = '',
                html = '',
                default = '',
                fields = [
                    prizz_extranet.models.process_action_field.ProcessActionField(
                        caption = '', 
                        type = '', 
                        value = '', 
                        name = '', 
                        values = [
                            null
                            ], 
                        required = True, )
                    ]
            )
        else:
            return ProcessAction(
        )
        """

    def testProcessAction(self):
        """Test ProcessAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
