# coding: utf-8

"""
    Prizz-Telecom Extranet API

    Prizz-Telecom Extranet API https://dev.prizz-telecom.fr/

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from prizz_extranet.models.client_legal_entity import ClientLegalEntity
from prizz_extranet.models.eligibility_result import EligibilityResult
from typing import Optional, Set
from typing_extensions import Self

class GetEligibility(BaseModel):
    """
    GetEligibility
    """ # noqa: E501
    wf: Optional[StrictInt] = Field(default=None, description="Workflow id")
    wfs: Optional[StrictStr] = Field(default=None, description="Workflow status")
    attrs: Optional[Dict[str, Any]] = Field(default=None, description="Attributes of the workflow")
    wftr: Optional[List[Dict[str, Any]]] = Field(default=None, description="Workflow transitions history")
    client: Optional[ClientLegalEntity] = None
    response: Optional[List[EligibilityResult]] = Field(default=None, description="Eligibility results")
    __properties: ClassVar[List[str]] = ["wf", "wfs", "attrs", "wftr", "client", "response"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetEligibility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of client
        if self.client:
            _dict['client'] = self.client.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in response (list)
        _items = []
        if self.response:
            for _item_response in self.response:
                if _item_response:
                    _items.append(_item_response.to_dict())
            _dict['response'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetEligibility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wf": obj.get("wf"),
            "wfs": obj.get("wfs"),
            "attrs": obj.get("attrs"),
            "wftr": obj.get("wftr"),
            "client": ClientLegalEntity.from_dict(obj["client"]) if obj.get("client") is not None else None,
            "response": [EligibilityResult.from_dict(_item) for _item in obj["response"]] if obj.get("response") is not None else None
        })
        return _obj


