# coding: utf-8

"""
    Prizz-Telecom Extranet API

    Prizz-Telecom Extranet API https://dev.prizz-telecom.fr/

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from prizz_extranet.models.process_message import ProcessMessage
from typing import Optional, Set
from typing_extensions import Self

class ProcessAttributesMessages(BaseModel):
    """
    ProcessAttributesMessages
    """ # noqa: E501
    operateur: Optional[List[ProcessMessage]] = None
    noc: Optional[List[ProcessMessage]] = None
    terrain: Optional[List[ProcessMessage]] = None
    __properties: ClassVar[List[str]] = ["operateur", "noc", "terrain"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessAttributesMessages from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in operateur (list)
        _items = []
        if self.operateur:
            for _item_operateur in self.operateur:
                if _item_operateur:
                    _items.append(_item_operateur.to_dict())
            _dict['operateur'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in noc (list)
        _items = []
        if self.noc:
            for _item_noc in self.noc:
                if _item_noc:
                    _items.append(_item_noc.to_dict())
            _dict['noc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in terrain (list)
        _items = []
        if self.terrain:
            for _item_terrain in self.terrain:
                if _item_terrain:
                    _items.append(_item_terrain.to_dict())
            _dict['terrain'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessAttributesMessages from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operateur": [ProcessMessage.from_dict(_item) for _item in obj["operateur"]] if obj.get("operateur") is not None else None,
            "noc": [ProcessMessage.from_dict(_item) for _item in obj["noc"]] if obj.get("noc") is not None else None,
            "terrain": [ProcessMessage.from_dict(_item) for _item in obj["terrain"]] if obj.get("terrain") is not None else None
        })
        return _obj


