# coding: utf-8

"""
    Prizz-Telecom Extranet API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from prizz_extranet.models.product import Product
from typing import Optional, Set
from typing_extensions import Self

class Service(BaseModel):
    """
    Service
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    unit_price_discount: Optional[StrictInt] = Field(default=None, alias="unitPriceDiscount")
    unit_price_discount_str: Optional[StrictStr] = Field(default=None, alias="unitPriceDiscountStr")
    house_number: Optional[StrictInt] = Field(default=None, alias="houseNumber")
    house_number_complement: Optional[StrictStr] = Field(default=None, alias="houseNumberComplement")
    street_name: Optional[StrictStr] = Field(default=None, alias="streetName")
    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    city_name: Optional[StrictStr] = Field(default=None, alias="cityName")
    insee_code: Optional[StrictStr] = Field(default=None, alias="inseeCode")
    create_date: Optional[datetime] = Field(default=None, alias="createDate")
    last_modified_date: Optional[datetime] = Field(default=None, alias="lastModifiedDate")
    attributes: Optional[Dict[str, Any]] = None
    quantity: Optional[StrictInt] = None
    unit_price: Optional[StrictInt] = Field(default=None, alias="unitPrice")
    unit_price_str: Optional[StrictStr] = Field(default=None, alias="unitPriceStr")
    unit: Optional[StrictStr] = None
    vat: Optional[StrictStr] = None
    recurrence: Optional[StrictStr] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    x: Optional[Union[StrictFloat, StrictInt]] = None
    y: Optional[Union[StrictFloat, StrictInt]] = None
    projection: Optional[StrictStr] = None
    product: Optional[Product] = None
    status: Optional[StrictStr] = None
    subscription_date: Optional[datetime] = Field(default=None, alias="subscriptionDate")
    activation_date: Optional[datetime] = Field(default=None, alias="activationDate")
    end_date: Optional[datetime] = Field(default=None, alias="endDate")
    termination_date: Optional[datetime] = Field(default=None, alias="terminationDate")
    service_contract_id: Optional[StrictInt] = Field(default=None, alias="serviceContractId")
    paid_until: Optional[datetime] = Field(default=None, alias="paidUntil")
    __properties: ClassVar[List[str]] = ["id", "name", "unitPriceDiscount", "unitPriceDiscountStr", "houseNumber", "houseNumberComplement", "streetName", "postalCode", "cityName", "inseeCode", "createDate", "lastModifiedDate", "attributes", "quantity", "unitPrice", "unitPriceStr", "unit", "vat", "recurrence", "latitude", "longitude", "x", "y", "projection", "product", "status", "subscriptionDate", "activationDate", "endDate", "terminationDate", "serviceContractId", "paidUntil"]

    @field_validator('recurrence')
    def recurrence_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['monthly', 'yearly', 'half-yearly', 'quaterly']):
            raise ValueError("must be one of enum values ('monthly', 'yearly', 'half-yearly', 'quaterly')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['new', 'staging', 'active', 'ending', 'terminated']):
            raise ValueError("must be one of enum values ('new', 'staging', 'active', 'ending', 'terminated')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['product'] = self.product.to_dict()
        # set to None if unit_price_discount (nullable) is None
        # and model_fields_set contains the field
        if self.unit_price_discount is None and "unit_price_discount" in self.model_fields_set:
            _dict['unitPriceDiscount'] = None

        # set to None if house_number (nullable) is None
        # and model_fields_set contains the field
        if self.house_number is None and "house_number" in self.model_fields_set:
            _dict['houseNumber'] = None

        # set to None if house_number_complement (nullable) is None
        # and model_fields_set contains the field
        if self.house_number_complement is None and "house_number_complement" in self.model_fields_set:
            _dict['houseNumberComplement'] = None

        # set to None if street_name (nullable) is None
        # and model_fields_set contains the field
        if self.street_name is None and "street_name" in self.model_fields_set:
            _dict['streetName'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if city_name (nullable) is None
        # and model_fields_set contains the field
        if self.city_name is None and "city_name" in self.model_fields_set:
            _dict['cityName'] = None

        # set to None if insee_code (nullable) is None
        # and model_fields_set contains the field
        if self.insee_code is None and "insee_code" in self.model_fields_set:
            _dict['inseeCode'] = None

        # set to None if last_modified_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_date is None and "last_modified_date" in self.model_fields_set:
            _dict['lastModifiedDate'] = None

        # set to None if attributes (nullable) is None
        # and model_fields_set contains the field
        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        # set to None if unit_price (nullable) is None
        # and model_fields_set contains the field
        if self.unit_price is None and "unit_price" in self.model_fields_set:
            _dict['unitPrice'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if vat (nullable) is None
        # and model_fields_set contains the field
        if self.vat is None and "vat" in self.model_fields_set:
            _dict['vat'] = None

        # set to None if recurrence (nullable) is None
        # and model_fields_set contains the field
        if self.recurrence is None and "recurrence" in self.model_fields_set:
            _dict['recurrence'] = None

        # set to None if latitude (nullable) is None
        # and model_fields_set contains the field
        if self.latitude is None and "latitude" in self.model_fields_set:
            _dict['latitude'] = None

        # set to None if longitude (nullable) is None
        # and model_fields_set contains the field
        if self.longitude is None and "longitude" in self.model_fields_set:
            _dict['longitude'] = None

        # set to None if x (nullable) is None
        # and model_fields_set contains the field
        if self.x is None and "x" in self.model_fields_set:
            _dict['x'] = None

        # set to None if y (nullable) is None
        # and model_fields_set contains the field
        if self.y is None and "y" in self.model_fields_set:
            _dict['y'] = None

        # set to None if projection (nullable) is None
        # and model_fields_set contains the field
        if self.projection is None and "projection" in self.model_fields_set:
            _dict['projection'] = None

        # set to None if activation_date (nullable) is None
        # and model_fields_set contains the field
        if self.activation_date is None and "activation_date" in self.model_fields_set:
            _dict['activationDate'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['endDate'] = None

        # set to None if termination_date (nullable) is None
        # and model_fields_set contains the field
        if self.termination_date is None and "termination_date" in self.model_fields_set:
            _dict['terminationDate'] = None

        # set to None if paid_until (nullable) is None
        # and model_fields_set contains the field
        if self.paid_until is None and "paid_until" in self.model_fields_set:
            _dict['paidUntil'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "unitPriceDiscount": obj.get("unitPriceDiscount"),
            "unitPriceDiscountStr": obj.get("unitPriceDiscountStr"),
            "houseNumber": obj.get("houseNumber"),
            "houseNumberComplement": obj.get("houseNumberComplement"),
            "streetName": obj.get("streetName"),
            "postalCode": obj.get("postalCode"),
            "cityName": obj.get("cityName"),
            "inseeCode": obj.get("inseeCode"),
            "createDate": obj.get("createDate"),
            "lastModifiedDate": obj.get("lastModifiedDate"),
            "attributes": obj.get("attributes"),
            "quantity": obj.get("quantity"),
            "unitPrice": obj.get("unitPrice"),
            "unitPriceStr": obj.get("unitPriceStr"),
            "unit": obj.get("unit"),
            "vat": obj.get("vat"),
            "recurrence": obj.get("recurrence"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "projection": obj.get("projection"),
            "product": Product.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "status": obj.get("status"),
            "subscriptionDate": obj.get("subscriptionDate"),
            "activationDate": obj.get("activationDate"),
            "endDate": obj.get("endDate"),
            "terminationDate": obj.get("terminationDate"),
            "serviceContractId": obj.get("serviceContractId"),
            "paidUntil": obj.get("paidUntil")
        })
        return _obj


